### ISSUE TITLE
Will there be any changes in the next time

### ISSUE THREAD

**Issue by roin93** [Guard13007/Particulars#1]
Hey
I like this Project.
Yeah. Will there be any changes in the next time? Some Extentions or something?

I would appreciate it!

**Comment by Guard13007** [comment]
I have no plans for it right now. If you have any ideas, I would be glad to look into it again.

**Comment by Guard13007** [comment]
@roin93 This project has been moved to https://gitea.guard13007.com/abandoned/Particulars and will be deleted from GitHub soon.
